version: '3'
services:
  canal-server:
    image: canal/canal-server:v1.1.4
    container_name: canal-server
    ports:
      - 11111:11111
    environment:
      - canal.instance.mysql.slaveId=12
      - canal.auto.scan=false
      - canal.destinations=example
      - canal.instance.master.address=192.168.33.2:3306
      - canal.instance.dbUsername=canal
      - canal.instance.dbPassword=canal
      - canal.mq.topic=example
      - canal.instance.filter.regex=.*\\..*
    volumes:
      - ./canal-server/conf/:/admin/canal-server/conf/
      - ./canal-server/logs/:/admin/canal-server/logs/