version: '3'
services:
  canal-server:
    image: canal/canal-server:v1.1.4
    container_name: canal-server
    ports:
      - 11111:11111
    depends_on:
      - mysql
    environment:
      - canal.destinations=test
      - canal.instance.master.address=rm-uf6ygt85a066ec9cg9o.mysql.rds.aliyuncs.com:3306
      - canal.instance.dbUsername=seres_db_dev_user_01
      - canal.instance.dbPassword=Serrs#dbsa@2010
      - canal.instance.filter.regex=.*\\..*
    volumes:
      - ./canal-server/logs/:/home/admin/canal-server/logs/