version: '3.8'
services:
#  elasticsearch:
#    image: elasticsearch:6.8.2
#    container_name: elasticsearch
#    restart: always
#    ports:
#      - 9200:9200
#      - 9300:9300
#    environment:
#      discovery.type: single-node
#      TZ: Asia/Shanghai
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1


#可以采用H2数据库存储,不用ES也行

  skywalking-oap-server:
    image: apache/skywalking-oap-server:8.8.0
    container_name: skywalking-oap-server
#    depends_on:
#      - elasticsearch
#    links:
#      - elasticsearch
    ports:
      - 11800:11800
      - 12800:12800
      - 1234:1234
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: 47.242.143.77:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "./bin/swctl", "ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  skywalking-ui:
    image: apache/skywalking-ui
    container_name: skywalking-ui
    depends_on:
      - skywalking-oap-server
    links:
      - skywalking-oap-server
    ports:
      - 8078:8080
    environment:
      SW_OAP_ADDRESS: skywalking-oap-server:12800
      TZ: Asia/Shanghai