version: '3.8'
services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
#    container_name: elasticsearch
#    ports:
#      - "9200:9200"
#    healthcheck:
#      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 10s
#    environment:
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1

  oap:
    image: apache/skywalking-oap-server:8.9.0
    container_name: oap
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
#    links:
#      - elasticsearch
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: ["CMD", "./bin/swctl", "ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: 8.141.149.177:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      JAVA_OPTS: "-Xms256m -Xmx256m"
    networks:
      - skywalking-network

  ui:
    image: apache/skywalking-ui:8.9.0
    container_name: ui
    depends_on:
      oap:
        condition: service_healthy
    links:
      - oap
    ports:
      - "8078:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800
    networks:
      - skywalking-network

networks:
  skywalking-network:
    driver: bridge